### ISSUE TITLE
Hi Elkarashily，may I ask some questions about the testcases file?

### ISSUE THREAD

**Issue by fzy-fzy** [karashily/Parallel-Simulated-Annealing#1]
We can see the first number of the text file is the amount of cells, and the second number is the amount of connected cells, is that right? So how about the numbers of rows and columns? Is this the size of the whole chip, or the size of a single cell? And what do these numbers mean which in the netlist?  For example, in the text file cm150a.txt，the second line is ‘ 2 18 2 ’，the third line is  ’ 9 1 29 15 26 30 28 2 27 31 ’，what do these numbers represent？Thank you very much.

**Comment by karashily** [comment]
Hello,

Each test case consists of:
The first line: the first number is the number of cells, and the second number is the number of connections in the whole chip, the third and fourth numbers are the number of rows and columns of the whole chip. Cells in the chips are assumed to be of the same size.
The rest of the file: each line represents a connection (from the number of connections in the first line), the first number is the number of cells connected by that connection, and the rest of the line is the index of each of those cells.

So, as an example, in the file "cm150a.txt", the second line means there are two cells are connected with the first connection, and those two cells are cells #18 and #2. The third line means there are nine cells connected with the second connection, and those nine cells are #1 #29 #15 #26... etc.

Let me know if you have any more questions or if anything is unclear.

**Comment by fzy-fzy** [comment]
Hi Karashily，


Your explanation is very clear and helpful，thank you so much.


Best
Zheng&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "karashily/Parallel-Simulated-Annealing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上9:06
***@***.***&gt;;
抄送:&nbsp;"Fu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [karashily/Parallel-Simulated-Annealing] Hi Elkarashily，may I ask some questions about the testcases file? (#1)





 
Hello,
 
Each test case consists of:
 The first line: the first number is the number of cells, and the second number is the number of connections in the whole chip, the third and fourth numbers are the number of rows and columns of the whole chip. Cells in the chips are assumed to be of the same size.
 The rest of the file: each line represents a connection (from the number of connections in the first line), the first number is the number of cells connected by that connection, and the rest of the line is the index of each of those cells.
 
So, as an example, in the file "cm150a.txt", the second line means there are two cells are connected with the first connection, and those two cells are cells #18 and #2. The third line means there are nine cells connected with the second connection, and those nine cells are #1 #29 #15 #26... etc.
 
Let me know if you have any more questions or if anything is unclear.
